# Build stage for frontend
FROM node:18-alpine AS frontend-builder
WORKDIR /app
COPY frontend .
RUN npm cache clean --force
RUN npm install --legacy-peer-deps --force
RUN npm run build

# Runtime stage for frontend
FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=frontend-builder /app/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
